// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DomReady(arg1) {
  return window['go']['scribe']['App']['DomReady'](arg1);
}

export function Greet() {
  return window['go']['scribe']['App']['Greet']();
}

export function LoadDocument(arg1) {
  return window['go']['scribe']['App']['LoadDocument'](arg1);
}
